config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :comments
  resources :rooms
  devise_for :users, controllers: 
  { 
    registrations: "users/registrations"
  }
  
  resources :rooms do
    resources :comments
  end
  root 'home#index'
  get 'home/sample'

end

app/models/room.rb
class Room < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :comments, dependent: :nullify
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :edit, :create, :update, :destroy ]
  before_action :authenticate_user!, except: [ :index, :show ]
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = current_user.rooms.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:user, :title, :roomtype, :address, :deposit, :rent_money, :image, :detail)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row text-center" style="margin-top:200px;">
	  <div class="col-md-10 col-md-offset-1 border-box">
		<h2>매물 등록하기</h2>
			<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon" style="padding-right: 30px;">제 목</span>
	      	<%= f.text_field :title, class: "form-control", placeholder: "ex)후문 앞 깨끗한 원룸" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon"style="padding-right: 20px;">방 유형</span>
	      	<%= f.text_field :roomtype, class: "form-control", placeholder: "ex)오피스텔" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon" style="padding-right: 30px;">주 소</span>
	      	<%= f.text_field :address, class: "form-control", placeholder: "ex)서울특별시 중구 필동 3가" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon" style="padding-right: 20px;">보증금</span>
	      	<%= f.text_field :deposit, placeholder: "ex)1000", class: "form-control" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon" style="padding-right: 30px;">월 세</span>
	      	<%= f.text_field :rent_money, placeholder: "ex)50", class: "form-control" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon" style="padding-right: 20px;">방 사진</span>
	      	<%= f.file_field :image, class: "form-control" %>
	    	</div>
	  	</label>
	  	<label class="input login-input g-mt-20">
	      <div class="input-group">
	      	<span class="input-group-addon">상세정보</span>
	      	<%= f.text_area :detail,  :maxlength=>"300", :size =>"50", placeholder: "상세정보 : 300자 이내로 작성해주세요", class: "form-control" %>
	    	</div>
	  	</label>
  <div class="row g-mb-20 g-mt-20">
		<div class="col-md-6 actions">
		  <%= f.submit "등록하기", class: "btn btn-xl" %>
		</div>
		<div class="g-mb-20 col-md-6">
		  <%= link_to '돌아가기', rooms_path, class: "btn btn-xl" %>
		</div>
	</div>
<% end %>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="container" id="portfolio" style="margin-top: 200px">
  <div class="row" style="margin-bottom: 50px;">
    <div class="col-lg-12 text-center">
      <h2 class="section-heading">방 보러가기</h2><br>
      <h3 class="section-subheading text-muted">자세한 내용을 보고 싶으시면 아래 방을 클릭하세요.</h3>
    </div>
  </div>
  <div class="row">
    <% @rooms.each do |room| %>
    <div class="col-md-4 col-sm-6 portfolio-item">
      <a href="/rooms/<%= room.id %>" class="portfolio-link" data-toggle="modal">
          <div class="portfolio-hover">
              <div class="portfolio-hover-content">
                  <i class="fa fa-search-plus fa-3x"></i>
              </div>
          </div>
          <img class="img-responsive" src="<%= room.image.url %>" alt="" style="width:360px; height:200px;">
      </a>
      <div class="portfolio-caption">
          <h4><%= room.title %></h4>
          <p class="text-muted">보증금: <%= room.deposit %>만원, 월세: <%= room.rent_money %>만원</p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="container">
	<div class="row" style="margin-top: 100px;">
	  <div><h1>방 자세히 보기</h1><hr></div>
		<div class="col-md-6">
		  <img class="img-responsive" style="width:100%; height:350px;" src = "<%= @room.image.url %>" alt="">
		</div>

		<div class="col-md-6">
			<div class="product-name">
				<h1><b><%= @room.title %></b></h1>
			</div>

			<p><%= @room.detail %></p><br />
      <div class="g-mb-40">
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 방 올린사람 : <b><%= @room.user.name %></b></p>
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 제 목 : <b><%= @room.title %></b></p>
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 방 유형 : <b><%= @room.roomtype %></b></p>
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 주 소: <b><%= @room.address %></b></p>
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 보증금 : <b><%= @room.deposit %>만원</b></p>
				<p><i class="fa fa-check-square-o" aria-hidden="true"></i> 월 세 : <b><%= @room.rent_money %>만원</b></p>
			</div>
		</div>
		<div style="text-align: right;">
			<% if current_user.id == @room.user_id %>
      	<%= link_to '삭제', @room, method: :delete, data:{confirm: "Are you sure?" }, class: "btn btn-xl" %>
      	<%= link_to '수정', edit_room_path(@room), class: "btn btn-xl" %>
    	<% end %>
		  <%= link_to '돌아가기', rooms_path, class: "btn btn-xl" %>
		</div>
	</div>
	<h3>댓 글</h3><hr>
  <% @room.comments.each do |comment| %>
    <div class="row" style="vertical-align: middle;">
      <div class="col-md-1">
	      <strong><i class="fa fa-user fa-4x" aria-hidden="true"></i></strong>
	      <p><%= comment.name %></p>
      </div>
      <div class="col-md-9">
      	<strong><i class="fa fa-commenting-o fa-2x" aria-hidden="true"></i></strong>
      	<%= comment.body %>
    	</div>
    	<div class="col-md-2">
    		<%= time_ago_in_words(comment.created_at) %>  / 
    		<% if current_user.name == comment.name %>
    			<strong><%= link_to '삭제하기', [comment.room, comment], method: :delete, data: { confirm: 'Are you sure?'} %></strong>
    		<% end %>
    	</div>
    </div>
  <% end %><hr>
	
	<h3>댓 글 작 성</h3>
	<% if current_user.nil? %>
		<div class="row" style="margin-bottom: 100px;">
			<h2>로그인 후 이용해주세요.</h2>
		</div>
	<% else %>
	  <%= form_for([@room, @room.comments.build]) do |f| %>
	    <div class="row" style="vertical-align: middle; margin-bottom:100px;">
	    	<div class="col-md-3">
	      	<%= f.label :'작성자' %> :
	      	<%= f.text_field :name %> 
	    	</div>
		    <div class="col-md-7">
	      	<%= f.text_area :body, :maxlength=>"200", :rows =>"3", :cols =>"80", placeholder: "200자이내로 댓글을 작성해 주세요" %>
		    </div>
		    <div class="col-md-2">
	      	<%= f.submit "댓글달기", class: "btn btn-xl" %>
		    </div>
	    </div>
	  <% end %> 
  <% end %>
</div>